### PR TITLE
Creating a task that uploads all possible variants to HockeyApp

### LINKED ISSUE #65: uploadToHockeyApp task to upload all product flavors
It would be great to have a way to upload all product flavours of an Android app with one gradle task. 
Like the assemble task assembles all variants the task could try to upload all variants.

### PR DESCRIPTION
**Pull request by jleidgens**
- A new task uploadToHockeyApp is defined that depends on all upload tasks
- If no AppId is supplied for a possible variant a message is printed instead of failing the gradle run

Fixes #65

### CODE REVIEW

**Comment by x2on** [comment]
Why shouldn't it throw a error if no appId is found?

**Comment by jleidgens** [comment]
Because if the build does not fail on a missing app id the task will only upload configured variants and ignore all variants that do not have an appId. 

Maybe I can change it in a way that the error is still thrown if only one variant is uploaded.

**Comment by x2on** [comment]
I would suggest to throw if you upload one variant. If you run it with uploadAll I would only throw a error if no appId was matching. Make sense?

**Comment by jleidgens** [comment]
Yes I will try to add this tomorrow

**Comment by x2on** [comment]
Sounds great :)

**Comment by jleidgens** [comment]
I implemented this. It is not the nicest way to solve this but it works.

**Comment by x2on** [comment]
Thanks a lot for your PR

**Pull request merged**
